Building a Mobile Menu Complete Feature
Elbie-em/CR-TRAINING-MOBILE-MENU pull request #1
Opened 2021-07-29 13:42 UTC by Elbie-em

#### This branch contains all the necessary files and requirements to complete the project specified[ here](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/7_mobile_menu.md)

- Linter configuration
- Initial HTML structure
- Added Mobile Menu
- Added Close button
- Set functionality for the open and close buttons
- Set functionality for mobile menu items

The live demo can be found [here](https://rawcdn.githack.com/Elbie-em/CR-TRAINING-MOBILE-MENU/feature/build-mobile-menu/public/index.html)

2021-08-02 17:14 UTC, trekab requested changes
Hi @Elbie-em, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
I think you did well with the hamburger menu button! :+1: However, there are some changes you could make to meet all the expected requirements. i.e:


## Required Changes ♻️
_Check the comments under the review._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

__[Treasure Kabareebe](https://trekab.github.io/#)__

2021-08-02 17:14 UTC, trekab commented on public/index.html
> +      </ul>
I think the correct part of the page should be displayed when the user clicks (or taps) any of the mobile menu options. :thinking: This would make page navigation on mobile devices easier and improve the user experience.

2021-08-02 17:14 UTC, trekab commented on README.md
> +## Live Demo
It is commendable that you deployed your project and shared the link to your deployed version. :clap: However, I think your README.md file would make your project easier to navigate if you added a screenshot of your live project. The `Contributing`, `Show your support`, and `Acknowledgements` sections would make it easy for other developers to contribute to your project. You may use [this template](https://github.com/microverseinc/readme-template).

2021-08-03 15:01 UTC, cyonii approved these changes
Hi @Elbie-em , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Slack: @[CY Kalu](https://microverse-students.slack.com/team/U01494U96FR)<br>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-05 13:34 UTC, merged